name: Bug Report
description: Having trouble with fetching a provider or module from OpenTofu?
labels: ["bug"]
body:
  - type: markdown
    attributes:
      label: Thank you for reporting an issue.
      description: Please provide a quick description of the problem you are encountering.
    validations:
      required: true

  - type: textarea
    id: tofu-version
    attributes:
      label: OpenTofu Version
      description: Run `tofu version` to show the version, and paste the result below. If you are not running the latest version of OpenTofu, please try upgrading because your issue may have already been fixed.
      render: shell
      placeholder: ...output of `tofu version`...
    validations:
      required: true

  - type: textarea
    id: opentofu-config
    attributes:
      label: OpenTofu Configuration Files
      description: 
      placeholder:
      value: |
        ```hcl
        // Snippet of HCL that can be used to help reproduce this problem
        ```
    validations:
      required: true
