name: Feature Request
description: Want to suggest something that's not yet supported?
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      label: Description of the feature you are looking for.
      description: Please provide a clear description of the feature you are looking for.  Please check existing issues to make sure this has not already been suggested.
    validations:
      required: true
