name: Submit new Provider Signing Key
description: Submit a new OpenTofu Provider Signing Key
title: "Provider Key: "
labels: ["provider-key", "submission"]
body:
  - type: input
    id: namespace
    attributes:
      label: Provider Namespace
      description: Github Username or Organization that contains Providers
    validations:
      required: true
  - type: textarea
    id: gpgkey
    attributes:
      label: Provider GPG Key
      description: Armoured public PGP key
  - type: checkboxes
    id: dco
    attributes:
      label: DCO
      options:
        - label: I sign this project's [DCO](https://developercertificate.org/)
          required: true
