name: Bump Versions and Publish - Prod

on:
  schedule:
    - cron: '5 * * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref }}

jobs:
  bump-versions:
    uses: opentofu/registry/.github/workflows/bump-versions.yml@main
    secrets: inherit
    with:
      environment: "Production"

  publish-versions:
    needs: bump-versions
    uses: opentofu/registry/.github/workflows/generate-and-deploy.yml@main
    secrets: inherit
    with:
      environment: "Production"
