name: Bump Versions and Publish - Prod

on:
  schedule:
    - cron: '5 * * * *'
  workflow_dispatch:

# Use global lock
#
# https://github.com/opentofu/registry/pull/272#discussion_r1511031778
concurrency:
  group: main

jobs:
  bump-versions:
    uses: opentofu/registry/.github/workflows/bump-versions.yml@main
    secrets: inherit
    with:
      environment: "Production"

  publish-versions:
    needs: bump-versions
    uses: opentofu/registry/.github/workflows/generate-and-deploy.yml@main
    secrets: inherit
    with:
      environment: "Production"
