name: Validate Module JSON

on:
  push:
    paths:
      - 'modules/**/*.json'
    branches:
      - 'module-**'

jobs:
  validate-metadata-module:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: actions/setup-go@v4
        with:
          go-version-file: './src/go.mod'

      - name: List updated filed
        id: updated
        uses: tj-actions/changed-files@v42
        with:
          files: modules/**/*.json

      - name: Validate JSON
        working-directory: ./src
        env:
          CHANGED_FILES: ${{ steps.updated.outputs.all_changed_files }}
        run: |
          for path in "$CHANGED_FILES"
          do
            go run ./cmd/validate/main.go module "$path"
          done
